Class FHIRDEMOPKG.FoundationProduction Extends Ens.Production 
{

XData ProductionDefinition
{
<Production Name="FHIRDEMOPKG.FoundationProduction" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>1</ActorPoolSize>

  <Item Name="HS.Util.Trace.Operations" Category="Scenario1,Scenario2,Scenario3" ClassName="HS.Util.Trace.Operations" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  
</Production>
}

}
