ARG IMAGE=intersystemsdc/irishealth-community

#ARG IMAGE=intersystemsdc/iris-community

FROM $IMAGE AS builder

ARG IRIS_PASSWORD
USER root   


WORKDIR /opt/irisapp
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /opt/irisapp

USER ${ISC_PACKAGE_MGRUSER}

COPY ./src ./src
COPY ./key ./key
COPY ./misc ./misc
COPY module.xml module.xml

COPY iris.script /tmp/iris.script


# run iris and initial 
RUN iris start IRIS \
	&& iris session IRIS < /tmp/iris.script \
	&& iris stop IRIS quietly

#RUN old=http://localhost:32783/crud/_spec && \
#	new=./swagger.yml && \
#	sed -i "s|$old|$new|g" /usr/irissys/csp/swagger-ui/index.html

FROM $IMAGE AS final


# COPY --chown=${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} ./data/durable /irisdata  

ADD --chown=${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} https://github.com/grongierisc/iris-docker-multi-stage-script/releases/latest/download/copy-data.py /irisdev/app/copy-data.py

 RUN --mount=type=bind,source=/,target=/builder/root,from=builder \
 --mount=type=bind,source=./data/durable,target=/irisdata \
	cp -f /builder/root/usr/irissys/iris.cpf /usr/irissys/iris.cpf && \
	python3 /irisdev/app/copy-data.py -c /usr/irissys/iris.cpf -d /builder/root/ 

# RUN --mount=type=bind,source=/,target=/builder/root,from=builder \
# --mount=type=bind,source=./data/durable,target=/irisdata:rw \
#	cp -f /builder/root/usr/irissys/iris.cpf /irisdata/irissys/iris.cpf && \
#	python3 /irisdev/app/copy-data.py -c /irisdata/irissys/iris.cpf -d /builder/root/ 